theme: jekyll-theme-slate
# site.github.title: St Andrews Software Development Guidance (draft)
# site.github.description: Draft Guidance for developers of software for research at the University of St Andrews
